### ISSUE TITLE
section marker not working after update

### ISSUE THREAD

**Issue by gnafrgb** [Aimarekin/Aimarekins-Spicetify-Extensions#12]
not sure if it's just me or the API issue. but the after the 2024/02/22 update this extension stop working. no section markers on the progress bar anymore.

this is a screenshot of all the extensions I've installed. use only the default theme. 

![Screenshot 2024-02-23 203603](https://github.com/Aimarekin/Aimarekins-Spicetify-Extensions/assets/72696475/5a961c35-2be8-42af-be68-7bebfae9779e)

**Comment by x-Misery** [comment]
Don't know when (or if) this will be fixed in the future, but downgrading spotify to 1.2.30 will fix it for now - [link](https://docs.google.com/spreadsheets/d/1wztO1L4zvNykBRw7X4jxP8pvo11oQjT0O5DvZ_-S4Ok/edit#gid=803394557)
And after downgrading ofc you should get spicetify back (open powershell and type **_spicetify backup apply_**)

**Comment by gnafrgb** [comment]
Thank you for the reply. So it's API side problem? Too bad to hear that. It's a quite fun extension to have in Spotify. 🥲

**Comment by x-Misery** [comment]
Spicetify.getAudioData (which is used for this and some other extensions like sort-plus) does not work after 1.2.30, I'm not a dev so I cannot say for sure if it's going to be fixed or if someone will find a workaround :(. Time will show
