### ISSUE TITLE
Auto Skip Bug

### ISSUE THREAD

**Issue by Phymiu** [Aimarekin/Aimarekins-Spicetify-Extensions#13]
Skip After Timestamp only work for first song.

**Comment by Aimarekin** [comment]
Can't reproduce - works fine for me. Any specifics of when it happens? I set the skip mark and it works for any next song just fine

**Comment by trepersec** [comment]
I have the same issue. Does spicetify provide logging because I don't see it anywhere. Here's all the info I can provide:

Operating System (Win10)
```
powershell> [Environment]::OSVersion
Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.19045.0 Microsoft Windows NT 10.0.19045.0
 ```
Spicetify version (latest as of today)
```
powershell> spicetify -v
2.36.12
````

Marketplace version (latest as of today)
```
v1.0.2
```

Apps installed (via marketplace)
- Adblock by CharlieS1103
- Skip After Timestamp by Aimrekin

Apps installed (manually)
- N/A

config-xpui.ini
```
[Setting]
prefs_path              = %appdata%\AppData\Roaming\Spotify\prefs
current_theme           = marketplace
color_scheme            = 
inject_css              = 1
overwrite_assets        = 0
spotify_path            = %appdata%\AppData\Roaming\Spotify
inject_theme_js         = 1
replace_colors          = 1
spotify_launch_flags    = 
check_spicetify_upgrade = 0
always_enable_devtools  = 0
check_spicetify_update  = 1

[Preprocesses]
remove_rtl_rule       = 1
expose_apis           = 1
disable_upgrade_check = 1
disable_sentry        = 1
disable_ui_logging    = 1

[AdditionalOptions]
extensions            = 
custom_apps           = marketplace
sidebar_config        = 1
home_config           = 1
experimental_features = 1

[Patch]

; DO NOT CHANGE!
[Backup]
version = 1.2.39.578.g0ea3f38b
with    = 2.36.12
```

Spotify logs are empty (i.e., %appdata%\Local\Temp\SpotifyErrorReport-<random-GUID>\Spotify_BridgeMessages_<timestamp>.json)
```
{
  "message_chunks": [
[]
  ],
  "loadEvents": []
}
```

Image 1 example of it not working (using percentage) on Windows
![image](https://github.com/Aimarekin/Aimarekins-Spicetify-Extensions/assets/45526820/3e827a11-fd13-454e-8614-b5092a115e7b)

Image 2 example of it not working (using timestamp) on Windows
![image](https://github.com/Aimarekin/Aimarekins-Spicetify-Extensions/assets/45526820/5f10f93c-f417-47b7-980b-5327dcff8f20)

Image 3 example of it not working but also the scale is off. The example shows me setting a skip using a separate audio of 28 minutes, but I go to a 3 minute song and but skip button is at the 60% mark on Ubuntu
![image](https://github.com/Aimarekin/Aimarekins-Spicetify-Extensions/assets/45526820/bd3c907b-1c02-49a4-9002-324468b90231)


A few additional comments:
- I use the spotify app with spicetify and marketplace as extensions, directly from their github repo and following their recommended installation recommendations
- I exclusively use marketplace, but I've tried installing it manually and adjusting the `config-xpui.ini ` file (after removing it from the marketplace) and the results were the same. 
- I use spicetify across multiple computers (all Win10) and physically separated networks, and still had the same issue
- I've tried signing into a separate spotify account, and still had the same issue
- On the Spotify app, I've selected Help > Troubleshooting > Reset App Data and Restart, and still had the same issue
- On the Sptofiy app, I've selected Help > Troubleshooting > Disable Hardware Acceleration and Restart, and still had the same issue
- I've uninstalled Spotify, reinstalled it, and still had the same issue
- I've opened up a virtual machine (VM), installed a fresh copy of Spotify, spicetify, and marketplace on Win11, and still had the same issue.
- I've opened up a VM, installed a fresh copy of Spotify, spicetify, and marketplace on Ubuntu, and still had the same issue

The only thing I did not test was installing spotify via Windows Store. If there are further diagnostic or troubleshooting steps you'd like me to conduct, please let me know. Thank you!

**Comment by Aimarekin** [comment]
@trepersec Turns out I completely forgot to upload the updated version of the extension, which is why it worked on my computer but not anyone else's. I've released the update and the extension should work again once your Spotify loads it again.

**Comment by Aimarekin** [comment]
Just confirmed the version released on marketplace is now working correctly - because I've abandoned these projects for a while and this repo is structured very poorly, I had to look for the working compiled code I've been using and merge it. The source code published on the main branch now no longer matches the compiled code though. Plan to fix some day
