### ISSUE TITLE
[Feature request] Export together with timings

### ISSUE THREAD

**Issue by Hexality** [Aimarekin/Aimarekins-Spicetify-Extensions#6]
A way to copy or export the lyrics together with its section timestamps.

**Comment by Aimarekin** [comment]
The extension is just meant to be used to quickly copy lyrics to paste them into other apps, not really for exporting lyrics - Is there any specific purpose/platform why you want to export timestamps?

**Comment by Hexality** [comment]
some times people use spotify as a way to get lyrics for songs they already have downloaded, having the ability to export/copy the lyrics together with its timestamps would be a nice addition.

**Comment by Aimarekin** [comment]
This is probably something better suited for other tools out of Spotify. Extracting timestamps would mean implementing another function to export structured lyrics instead of raw text, which would also have to follow conventions for these files.

Adding the lyrics to the tracks is also something that another program should do. There's metadata editors that will download and apply lyrics for you.
